# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: './mvnw clean package'

#- task: Maven@3
#  inputs:
#    mavenPomFile: 'pom.xml'
#    goals: 'clean package'
#    publishJUnitResults: false
#    javaHomeOption: 'JDKVersion'
#    jdkVersionOption: '1.8'
#    mavenVersionOption: 'Default'
#    mavenAuthenticateFeed: false
#    sonarQubeRunAnalysis: false
#    sqMavenPluginVersionChoice: 'latest'

- task: GitHubRelease@0
  inputs:
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    isDraft: true
    target: '$(Build.SourceVersion)'
    assets: '$(Build.ArtifactStagingDirectory)/target/LogChain*.jar'
    tagSource: 'auto'
    title: 'Draft Release by Azure DevOps'
    gitHubConnection: githubstevenbeeckman